# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haveibeenpwned', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwnedpassword',
            name='hash',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
